#!/bin/sh

# Check if the first argument is "admin"
if [ "$1" = "admin" ]; then
    # Call the original passwd command with all original arguments except the first one
    /bin/passwd_original "${@:2}"
else
    # Show an error message
    echo "Please use the PiFi app to change the root password to make sure it stays in sync and doesn't break the app."
fi
