src/gz pifi_packages https://downloads.pifi.org/1.5.2
src/gz openwrt_core https://downloads.openwrt.org/releases/24.10.1/targets/bcm27xx/bcm2712/packages
src/gz openwrt_base https://downloads.openwrt.org/releases/24.10.1/packages/aarch64_cortex-a76/base
src/gz openwrt_luci https://downloads.openwrt.org/releases/24.10.1/packages/aarch64_cortex-a76/luci
src/gz openwrt_packages https://downloads.openwrt.org/releases/24.10.1/packages/aarch64_cortex-a76/packages
src/gz openwrt_routing https://downloads.openwrt.org/releases/24.10.1/packages/aarch64_cortex-a76/routing
src/gz openwrt_telephony https://downloads.openwrt.org/releases/24.10.1/packages/aarch64_cortex-a76/telephony
