#!/bin/sh

while true; do
    wg_handshake=$(wg show | grep -q "handshake" && echo "1" || echo "0")
    openvpn_status=$(/etc/init.d/openvpn status | grep -q "running" && echo "1" || echo "0")

    if [ "$wg_handshake" -eq "1" ] || [ "$openvpn_status" -eq "1" ]; then
        echo 1 > /tmp/vpnactive
    else
        echo 0 > /tmp/vpnactive
    fi

    /bin/sh /etc/sysp/pifi_blink
    /bin/sh /etc/sysp/pifi_apstatus

    sleep 30
done
