#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command sh /etc/sysp/pifi_radioup
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
